add files for review
muza222/keyboardracing pull request #1
Opened 2023-06-24 15:55 UTC by muza222

2023-06-25 20:07 UTC, vsminkov requested changes
Оставил несколько вопросов. Всё что помечено "мысли в слух" скорее просто комментарий/напутствие

2023-06-25 20:07 UTC, vsminkov commented on src/main/java/com/murzik/keyboardrace/client/GameFrame.java
> +        try {
Мы на лекциях проходили одну из конструкций языка, которая бы тут могла помочь. На что я намекаю? 😀

2023-06-25 20:07 UTC, vsminkov commented on src/main/java/com/murzik/keyboardrace/client/GameFrame.java
> +                    } catch (NumberFormatException e) {
(Просто мысли вслух) в целом можно `try` заменить на `if`. Кажется валидация тут не очень сложная, а получилось бы чуточку эффективнее.

2023-06-25 20:07 UTC, vsminkov commented on src/main/java/com/murzik/keyboardrace/client/GameFrame.java
> +                    while (text.equals("")) {
(Тоже мысль в слух) Рекомендую использовать `CONST.equals(x)` вместо `x.equals(CONST)` т.к заодно может уберечь от случайного `NPE`

2023-06-25 20:07 UTC, vsminkov commented on src/main/java/com/murzik/keyboardrace/client/GameFrame.java
> +            throw new RuntimeException(e);
Советую потом попробовать тут и ниже выкинуть свой класс эксепшнов чтобы сделать возможной красивую обработку ошибок выше.

2023-06-25 20:07 UTC, vsminkov commented on src/main/java/com/murzik/keyboardrace/client/GameFrame.java
> +            throw new RuntimeException(e);
(Мысли в слух) Это не всегда возможно, но лучше стараться избегать выкидывания ошибок из конструктора. Например в этом случае весть класс похож на некий `AutoCloseable` — есть явная стадия выделения ресурсов и их закрытия. Можно было бы вынести открытие сокета в отдельный метод а санружи управлять неким auto-cloaseble объектом

2023-06-25 20:07 UTC, vsminkov commented on src/main/java/com/murzik/keyboardrace/server/ClientServerCommunication.java
> +class ClientServerCommunication extends Thread {
А какой ещё есть способ определить работу, которую необходимо проделать потоку и был бы он тут применим?

2023-06-25 20:07 UTC, vsminkov commented on src/main/java/com/murzik/keyboardrace/client/LaunchFrame.java
> +    private final String[] names = {
Почему такое поле может быть небезопасным? И какую можно тут ещё конструкцию использовать?

2023-06-26 10:29 UTC, turbomuza commented on src/main/java/com/murzik/keyboardrace/server/ClientServerCommunication.java
> +class ClientServerCommunication extends Thread {
Можно вместо наследования от класса Thread сделать класс, класс реализующий интерфейс Runnable, где переопределен метод run().

2023-06-26 10:30 UTC, turbomuza commented on src/main/java/com/murzik/keyboardrace/client/LaunchFrame.java
> +    private final String[] names = {
изза констант? ну можно енамы использовать в качестве хранения такого рода данных

2023-06-26 10:31 UTC, turbomuza commented on src/main/java/com/murzik/keyboardrace/client/LaunchFrame.java
> +    private final String[] names = {
а ваще можно порт и ip прикрутить как локальные переменные

2023-06-26 10:31 UTC, turbomuza commented on src/main/java/com/murzik/keyboardrace/client/GameFrame.java
> +            throw new RuntimeException(e);
ОК :)

2023-06-26 10:32 UTC, turbomuza commented on src/main/java/com/murzik/keyboardrace/client/GameFrame.java
> +        try {
тут не совсем понял а как по другому? что-то не врубаюсь ))))

2023-06-26 13:07 UTC, vsminkov commented on src/main/java/com/murzik/keyboardrace/client/GameFrame.java
> +        try {
Обсудили в личке, всё ок :)

2023-06-26 13:08 UTC, vsminkov commented on src/main/java/com/murzik/keyboardrace/client/LaunchFrame.java
> +    private final String[] names = {
Пойдёт. Я имел ввиду скорее что массивы небезопасны т.к их можно модифицировать и можно использовать иммутабельные коллекции

2023-06-26 13:12 UTC, vsminkov approved these changes

2023-10-01 20:57 UTC, merged